# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 090e9eb104b7d99f4c81a3cf95842229bdac6b41e68b66598d8a13cc3fbcb01549a2ed67de641014964ee1c1c5a829f3df1c9a7dc88dcfc4acb6963982fb99c0

test:
  secret_key_base: d267560e86c657302ea38d9bab0ae8279e9b06531257c3fbbb44b3d05724f35dcc9c0cf9c871b6b8ef7f42d66a7b29adf75ac9ce531fd06a3167c51bbe539749

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
